before_script:
  - echo "{\"auths\":{\"$TARGET_REGISTRY_HOST\":{\"username\":\"$TARGET_REGISTRY_USER\",\"password\":\"$TARGET_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  - >
    export ITSM_VERSION="$(grep '^ARG ITSM_VERSION' Dockerfile | cut -d= -f2)"
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CI_DEBUG_TRACE: 'true'

stages:
  - Build
  - Publish



"Build container":
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: Build
  script:
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --no-push
  only:
    - main
    - tags

"Push to registry":
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: Publish
  script:
    - /kaniko/executor --context ${CI_PROJECT_DIR} --dockerfile ${CI_PROJECT_DIR}/Dockerfile --destination ${CI_REGISTRY_IMAGE}/itsm-ng:${ITSM_VERSION}-${CI_COMMIT_TAG}
  only:
    - tags
  needs:
    - "Build container"
